post_install()
{
   user_home=$(getent passwd "$SUDO_USER" | cut -d: -f6)
   mkdir -p "$user_home/.local/share/arcos"
   rm -rf "$user_home/.local/share/arcos/arcos-desktop"
   cp -rf "/etc/skel/.local/share/arcos/arcos-desktop" "$user_home/.local/share/arcos/arcos-desktop"
   chown -R "$SUDO_USER:$SUDO_USER" "$user_home/.local/share/arcos"
   chmod 755 "$user_home/.local/share/arcos" -R
}

post_upgrade()
{
    post_install
}


